"""Add user_id column to products table

Revision ID: fc5ffd05cc10
Revises: 40999d97bb84
Create Date: 2024-07-15 18:19:46.766446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc5ffd05cc10'
down_revision = '40999d97bb84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('image',
               existing_type=sa.BLOB(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_constraint('products_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('current_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('products_ibfk_1', 'users', ['current_user_id'], ['id'])
        batch_op.alter_column('image',
               existing_type=sa.String(length=255),
               type_=sa.BLOB(),
               existing_nullable=False)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
